spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}  # Формат: jdbc:postgresql://host:port/db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}  # Логин (по умолчанию 'postgres')
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}  # Пароль (по умолчанию 'postgres')
    driver-class-name: org.postgresql.Driver  # Драйвер PostgreSQL

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true      # Показывать SQL-запросы в логах (для разработки)

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml  # Путь к главному changelog-файлу
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379

grpc:
  profile-service:
    domain: ${PROFILE_SERVICE_DOMAIN:localhost}