services:
  post-service:
    build:
      context: ./post-service
      dockerfile: Dockerfile
    container_name: post-service
    hostname: post-service
    restart: unless-stopped
    expose:
      - "8080"

  api-gateway:
    image: nginx:alpine
    container_name: api-gateway
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./api-gateway-service:/etc/nginx/conf.d
    depends_on:
      - post-service