services:
  app:
    build:
      context: ./post-service/Post Service
      dockerfile: ../Dockerfile
    container_name: post-service
    hostname: post-service
    restart: unless-stopped
    ports:
      - "8080:8080"