spring:
  application:
    name: post-service

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - health
          - info
  endpoint:
    health:
      show-details: always
    mappings:
      enabled: true

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG