spring:
  application:
    name: post-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/post_db}  # Формат: jdbc:postgresql://host:port/db
    username: ${SPRING_DATASOURCE_USERNAME:postgres}  # Логин (по умолчанию 'postgres')
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}  # Пароль (по умолчанию 'postgres')
    driver-class-name: org.postgresql.Driver  # Драйвер PostgreSQL

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true      # Показывать SQL-запросы в логах (для разработки)

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml  # Путь к главному changelog-файлу
    user: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - health
          - info
  endpoint:
    health:
      show-details: always
    mappings:
      enabled: true

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG