spring:
  application:
    name: post-service

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG

server:
  servlet:
    context-path: /