ktor:
  application:
    modules:
      - com.github.fedverdev.ApplicationKt.module
  deployment:
    port: 8080

database:
  host: ${DATABASE_HOST:localhost}
  port: 5432
  password: postgres
  username: postgres
  name: ${DATABASE_NAME:profile_db}